export type Locale = 'pt' | 'es' | 'en'
export type LocalizedText = Record<Locale, string>
export type PartyItem = { id: string; category: 'rental' | 'decoration' | 'pickup'; audience: 'kids' | 'adults'; name: LocalizedText; description: LocalizedText; image: string; images?: string[]; price?: string }

const photos = {
  captain: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/boys%203-q7NJLbbWpXv6t2kXb8uX6dmvpTWkhn.jpg',
  bear: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/boys1-3vsq6TuSYULpWwC99rZXeZldnkfLfI.jpg',
  baby: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/boys2-MTbQuuVAGQMU4rmu2PsxKVNhWqQ2UM.jpg',
  farm: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/girls3-eeEBI3WDn4GmKKSyVJuYU6Ma9f1z1D.jpg',
  shop: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/girls4-SiRdiFW6lLZ2xJOuimrPv8UJElaNlV.jpg',
  butterfly: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/girls2-5gWTJN6RxYIew8kDZYsGnSx3xLaIDO.jpg',
  arch: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/girls1-aiT5gxG1kApSN5xJ82ALNRz45zfFaB.jpg',
}

export const items: PartyItem[] = [
  { id: 'boys-1', category: 'decoration', audience: 'kids', name: { pt: 'Capitão América', es: 'Capitán América', en: 'Captain America' }, description: { pt: 'Uma produção heroica com balões, painéis e mesa temática.', es: 'Una producción heroica con globos, paneles y mesa temática.', en: 'A heroic setup with balloons, backdrops and a themed table.' }, image: photos.captain, images: [photos.captain, photos.bear] },
  { id: 'boys-2', category: 'decoration', audience: 'kids', name: { pt: 'Ursinho aviador', es: 'Osito aviador', en: 'Little pilot bear' }, description: { pt: 'Uma festa suave e criativa para celebrar o primeiro ano.', es: 'Una fiesta dulce y creativa para celebrar el primer año.', en: 'A soft and creative party for a first birthday.' }, image: photos.bear, images: [photos.bear, photos.captain] },
  { id: 'boys-3', category: 'decoration', audience: 'kids', name: { pt: 'Baby Medeiros', es: 'Baby Medeiros', en: 'Baby Medeiros' }, description: { pt: 'Cores naturais, arco orgânico e um cenário cheio de personalidade.', es: 'Colores naturales, arco orgánico y un escenario con personalidad.', en: 'Natural colors, an organic balloon arch and a memorable backdrop.' }, image: photos.baby },
  { id: 'girls-1', category: 'decoration', audience: 'kids', name: { pt: 'Fazendinha delicada', es: 'Granjita delicada', en: 'Sweet little farm' }, description: { pt: 'Uma celebração campestre com flores, bichinhos e muito charme.', es: 'Una celebración campestre con flores, animalitos y mucho encanto.', en: 'A charming countryside celebration with flowers and farm animals.' }, image: photos.farm },
  { id: 'girls-2', category: 'decoration', audience: 'adults', name: { pt: 'Doce loja', es: 'Dulce tienda', en: 'Sweet shop' }, description: { pt: 'Uma mesa cor-de-rosa, lúdica e pronta para encantar.', es: 'Una mesa rosa, lúdica y lista para encantar.', en: 'A playful pink dessert table made to delight.' }, image: photos.shop },
  { id: 'girls-3', category: 'decoration', audience: 'adults', name: { pt: 'Jardim de borboletas', es: 'Jardín de mariposas', en: 'Butterfly garden' }, description: { pt: 'Flores, borboletas e uma composição leve para momentos especiais.', es: 'Flores, mariposas y una composición ligera para momentos especiales.', en: 'Flowers, butterflies and a light setup for special moments.' }, image: photos.butterfly },
  { id: 'girls-4', category: 'decoration', audience: 'adults', name: { pt: 'Arco rosa ao ar livre', es: 'Arco rosa al aire libre', en: 'Outdoor pink arch' }, description: { pt: 'Um cenário romântico para celebrar em meio à natureza.', es: 'Un escenario romántico para celebrar rodeado de naturaleza.', en: 'A romantic setting for celebrating surrounded by nature.' }, image: photos.arch },
  { id: 'rental-candles', category: 'rental', audience: 'adults', name: { pt: 'Kit de boleiras', es: 'Kit de bandejas', en: 'Cake stand kit' }, description: { pt: 'Peças selecionadas para montar uma mesa elegante.', es: 'Piezas seleccionadas para una mesa elegante.', en: 'Selected pieces for an elegant dessert table.' }, image: photos.shop },
  { id: 'pickup-rainbow', category: 'pickup', audience: 'kids', name: { pt: 'Kit arco-íris', es: 'Kit arcoíris', en: 'Rainbow kit' }, description: { pt: 'Tudo organizado para você pegar e montar.', es: 'Todo listo para recoger y montar.', en: 'Everything organized for you to pick up and style.' }, image: photos.baby },
]

export const testimonials = [
  { initial: 'M', name: { pt: 'Mariana', es: 'Mariana', en: 'Mariana' }, quote: { pt: 'Depoimento de exemplo — substitua por uma história real.', es: 'Depoimento de ejemplo — reemplaza por una historia real.', en: 'Example testimonial — replace with a real story.' } },
  { initial: 'L', name: { pt: 'Luciana', es: 'Luciana', en: 'Luciana' }, quote: { pt: 'Depoimento de exemplo — substitua por uma história real.', es: 'Depoimento de ejemplo — reemplaza por una historia real.', en: 'Example testimonial — replace with a real story.' } },
  { initial: 'R', name: { pt: 'Rafaela', es: 'Rafaela', en: 'Rafaela' }, quote: { pt: 'Depoimento de exemplo — substitua por uma história real.', es: 'Depoimento de ejemplo — reemplaza por una historia real.', en: 'Example testimonial — replace with a real story.' } },
]
export const PARTIES_COUNT = 0
export const WHATSAPP_NUMBER = '55[NUMERO]'
export const whatsappUrl = (message: string) => `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`
export const categoryLabel = (category: PartyItem['category'], t: (typeof translations)[Locale]) => ({ rental: t.categories.rental, decoration: t.categories.decoration, pickup: t.categories.pickup }[category])

const common = {
  pt: { nav: { portfolio: 'Portfólio', how: 'Como funciona', about: 'Sobre nós', faq: 'Dúvidas', contact: 'Contato' }, hero: { eyebrow: 'Festas que viram memória', title: 'Pequenos detalhes. Grandes celebrações.', body: 'Decoração afetiva e peças encantadoras para deixar cada aniversário com a cara de quem você ama.', cta: 'Falar no WhatsApp', secondary: 'Ver portfólio', handmade: 'Feito à mão' }, categories: { eyebrow: 'Do seu jeito', title: 'Escolha como celebrar', rental: 'Aluguel de Peças', rentalBody: 'Peças únicas para você criar sua composição.', decoration: 'Decoração', decorationBody: 'Montamos tudo com cuidado e personalidade.', pickup: 'Pegue e Monte', pickupBody: 'Kits práticos para celebrar no seu ritmo.' }, portfolio: { eyebrow: 'Inspire-se', title: 'Um pouco do que fazemos', all: 'Todos', kids: 'Crianças', adults: 'Adultos', rental: 'Aluguel', decoration: 'Decoração', pickup: 'Pegue e monte', action: 'Pedir no WhatsApp', sms: 'Enviar SMS', add: 'Adicionar ao pedido', added: 'Adicionado', starting: 'A partir de' }, how: { eyebrow: 'Leve e gostoso', title: 'Como funciona', steps: [{ title: 'Conte seu sonho', body: 'Fale com a gente sobre a data, o tema e o que você imaginou.' }, { title: 'A gente cria', body: 'Montamos uma proposta cheia de detalhes e carinho para você.' }, { title: 'É hora de celebrar', body: 'Você recebe tudo pronto para viver um dia inesquecível.' }] }, about: { eyebrow: 'Feito com carinho', title: 'Festas com alma, beleza e leveza.', body: 'A [NOME] nasceu para transformar momentos simples em histórias que ficam. Acreditamos que celebrar é cuidar dos detalhes — e que cada família merece uma festa tão especial quanto suas memórias.', signature: 'Com carinho, equipe [NOME]' }, testimonials: { eyebrow: 'Quem celebra com a gente', title: 'Depoimentos', count: '+0 festas realizadas' }, faq: { eyebrow: 'Ainda ficou alguma dúvida?', title: 'Perguntas frequentes', questions: [{ q: 'Com quanto tempo devo reservar?', a: 'Recomendamos reservar com 30 dias de antecedência.' }, { q: 'Vocês atendem a minha cidade?', a: 'Atendemos a região e também enviamos kits Pegue e Monte.' }, { q: 'Posso personalizar meu pedido?', a: 'Sim! Adoramos criar propostas únicas.' }] }, contact: { eyebrow: 'Vamos criar juntos?', title: 'Sua próxima festa começa aqui.', body: 'Fale com a gente e conte como podemos deixar seu momento ainda mais especial.', cta: 'Chamar no WhatsApp', sms: 'Enviar SMS', date: 'Data da festa', theme: 'Tema', city: 'Cidade', category: 'Categoria', sendQuote: 'Enviar orçamento pelo WhatsApp', order: 'Meu pedido', sendOrder: 'Enviar pedido pelo WhatsApp', remove: 'Remover', choose: 'Escolha uma categoria' }, instagram: 'Siga @donali.party no Instagram', instagramButton: 'Abrir Instagram', footer: 'Feito para celebrar o que realmente importa.' },
  es: { nav: { portfolio: 'Portafolio', how: 'Cómo funciona', about: 'Sobre nosotros', faq: 'Preguntas', contact: 'Contacto' }, hero: { eyebrow: 'Fiestas que se vuelven recuerdos', title: 'Pequeños detalles. Grandes celebraciones.', body: 'Decoración afectiva y piezas encantadoras para hacer cada cumpleaños único.', cta: 'Hablar por WhatsApp', secondary: 'Ver portafolio', handmade: 'Hecho a mano' }, categories: { eyebrow: 'A tu manera', title: 'Elige cómo celebrar', rental: 'Alquiler de piezas', rentalBody: 'Piezas únicas para crear tu composición.', decoration: 'Decoración', decorationBody: 'Montamos todo con cuidado y personalidad.', pickup: 'Recoge y monta', pickupBody: 'Kits prácticos para celebrar a tu ritmo.' }, portfolio: { eyebrow: 'Inspírate', title: 'Un poco de lo que hacemos', all: 'Todos', kids: 'Kids', adults: 'Adultos', rental: 'Alquiler', decoration: 'Decoración', pickup: 'Recoge y monta', action: 'Pedir por WhatsApp', sms: 'Enviar SMS', add: 'Añadir al pedido', added: 'Añadido', starting: 'Desde' }, how: { eyebrow: 'Fácil y bonito', title: 'Cómo funciona', steps: [{ title: 'Cuéntanos tu sueño', body: 'Háblanos de la fecha, el tema y lo que imaginaste.' }, { title: 'Nosotros creamos', body: 'Preparamos una propuesta llena de detalles y cariño.' }, { title: 'Es hora de celebrar', body: 'Recibes todo listo para vivir un día inolvidable.' }] }, about: { eyebrow: 'Hecho con cariño', title: 'Fiestas con alma, belleza y ligereza.', body: '[NOMBRE] nació para transformar momentos simples en historias que permanecen.', signature: 'Con cariño, equipo [NOMBRE]' }, testimonials: { eyebrow: 'Quienes celebran con nosotros', title: 'Testimonios', count: '+0 fiestas realizadas' }, faq: { eyebrow: '¿Aún tienes dudas?', title: 'Preguntas frecuentes', questions: [{ q: '¿Con cuánto tiempo debo reservar?', a: 'Recomendamos reservar con 30 días de antelación.' }, { q: '¿Atienden mi ciudad?', a: 'Atendemos la región y también enviamos kits Recoge y monta.' }, { q: '¿Puedo personalizar mi pedido?', a: '¡Sí! Nos encanta crear propuestas únicas.' }] }, contact: { eyebrow: '¿Creamos juntos?', title: 'Tu próxima fiesta empieza aquí.', body: 'Cuéntanos cómo podemos hacer tu momento más especial.', cta: 'Llamar por WhatsApp', sms: 'Enviar SMS', date: 'Fecha de la fiesta', theme: 'Tema', city: 'Ciudad', category: 'Categoría', sendQuote: 'Enviar presupuesto por WhatsApp', order: 'Mi pedido', sendOrder: 'Enviar pedido por WhatsApp', remove: 'Quitar', choose: 'Elige una categoría' }, instagram: 'Sigue a @donali.party en Instagram', instagramButton: 'Abrir Instagram', footer: 'Hecho para celebrar lo que realmente importa.' },
  en: { nav: { portfolio: 'Portfolio', how: 'How it works', about: 'About us', faq: 'FAQ', contact: 'Contact' }, hero: { eyebrow: 'Parties that become memories', title: 'Small details. Big celebrations.', body: 'Thoughtful styling and charming pieces to make every birthday feel personal.', cta: 'Chat on WhatsApp', secondary: 'View portfolio', handmade: 'Handmade' }, categories: { eyebrow: 'Your way', title: 'Choose how to celebrate', rental: 'Piece rental', rentalBody: 'Unique pieces to create your own setup.', decoration: 'Decoration', decorationBody: 'We style everything with care and personality.', pickup: 'Pick up & style', pickupBody: 'Practical kits to celebrate at your pace.' }, portfolio: { eyebrow: 'Get inspired', title: 'A little of what we do', all: 'All', kids: 'Kids', adults: 'Adults', rental: 'Rental', decoration: 'Decoration', pickup: 'Pick up & style', action: 'Ask on WhatsApp', sms: 'Send SMS', add: 'Add to order', added: 'Added', starting: 'From' }, how: { eyebrow: 'Easy and lovely', title: 'How it works', steps: [{ title: 'Tell us your dream', body: 'Share the date, theme and everything you imagined.' }, { title: 'We create', body: 'We prepare a thoughtful proposal made just for you.' }, { title: 'Time to celebrate', body: 'Everything arrives ready for an unforgettable day.' }] }, about: { eyebrow: 'Made with care', title: 'Parties with soul, beauty and ease.', body: '[NOME] was born to turn simple moments into stories that stay.', signature: 'With care, the [NOME] team' }, testimonials: { eyebrow: 'Celebrating with us', title: 'Testimonials', count: '+0 parties celebrated' }, faq: { eyebrow: 'Still have questions?', title: 'Frequently asked questions', questions: [{ q: 'How early should I book?', a: 'We recommend booking 30 days in advance.' }, { q: 'Do you serve my city?', a: 'We serve the region and also ship Pick up & style kits.' }, { q: 'Can I customize my order?', a: 'Yes! We love creating unique proposals.' }] }, contact: { eyebrow: 'Shall we create together?', title: 'Your next party starts here.', body: 'Tell us how we can make your moment more special.', cta: 'Chat on WhatsApp', sms: 'Send SMS', date: 'Party date', theme: 'Theme', city: 'City', category: 'Category', sendQuote: 'Send quote on WhatsApp', order: 'My order', sendOrder: 'Send order on WhatsApp', remove: 'Remove', choose: 'Choose a category' }, instagram: 'Follow @donali.party on Instagram', instagramButton: 'Open Instagram', footer: 'Made to celebrate what truly matters.' }
} as const
export const translations = common
export const heroImages = Object.values(photos)
