export type Locale = 'pt' | 'es' | 'en'

export type LocalizedText = Record<Locale, string>

export type PartyItem = {
  id: string
  category: 'rental' | 'decoration' | 'pickup'
  name: LocalizedText
  description: LocalizedText
  image: string
}

export const items: PartyItem[] = [
  { id: '01', category: 'rental', name: { pt: 'Arco-íris de balões', es: 'Arcoíris de globos', en: 'Rainbow balloon arch' }, description: { pt: 'Cores alegres para transformar a mesa principal.', es: 'Colores alegres para transformar la mesa principal.', en: 'Joyful colors to transform the main table.' }, image: '/placeholder.jpg' },
  { id: '02', category: 'decoration', name: { pt: 'Bosque encantado', es: 'Bosque encantado', en: 'Enchanted forest' }, description: { pt: 'Uma festa delicada, natural e cheia de encanto.', es: 'Una fiesta delicada, natural y llena de encanto.', en: 'A delicate, natural celebration full of wonder.' }, image: '/placeholder.jpg' },
  { id: '03', category: 'pickup', name: { pt: 'Kit safari', es: 'Kit safari', en: 'Safari kit' }, description: { pt: 'Tudo pronto para você montar uma aventura em casa.', es: 'Todo listo para montar una aventura en casa.', en: 'Everything ready for an adventure at home.' }, image: '/placeholder.jpg' },
  { id: '04', category: 'rental', name: { pt: 'Mesa dos sonhos', es: 'Mesa de ensueño', en: 'Dream table' }, description: { pt: 'Peças selecionadas para uma composição inesquecível.', es: 'Piezas seleccionadas para una composición inolvidable.', en: 'Curated pieces for an unforgettable setup.' }, image: '/placeholder.jpg' },
  { id: '05', category: 'decoration', name: { pt: 'Jardim encantado', es: 'Jardín encantado', en: 'Enchanted garden' }, description: { pt: 'Flores, texturas e detalhes feitos para celebrar.', es: 'Flores, texturas y detalles hechos para celebrar.', en: 'Flowers, textures and details made to celebrate.' }, image: '/placeholder.jpg' },
  { id: '06', category: 'pickup', name: { pt: 'Festa arco-íris', es: 'Fiesta arcoíris', en: 'Rainbow party' }, description: { pt: 'Um kit colorido para criar memórias especiais.', es: 'Un kit colorido para crear recuerdos especiales.', en: 'A colorful kit to create special memories.' }, image: '/placeholder.jpg' },
]

export const translations = {
  pt: {
    nav: { portfolio: 'Portfólio', how: 'Como funciona', about: 'Sobre nós', faq: 'Dúvidas', contact: 'Contato' },
    hero: { eyebrow: 'Festas que viram memória', title: 'Pequenos detalhes. Grandes celebrações.', body: 'Decoração afetiva e peças encantadoras para deixar cada aniversário com a cara de quem você ama.', cta: 'Falar no WhatsApp', secondary: 'Ver portfólio' },
    categories: { eyebrow: 'Do seu jeito', title: 'Escolha como celebrar', rental: 'Aluguel de Peças', rentalBody: 'Peças únicas para você criar sua composição.', decoration: 'Decoração', decorationBody: 'Montamos tudo com cuidado e personalidade.', pickup: 'Pegue e Monte', pickupBody: 'Kits práticos para celebrar no seu ritmo.' },
    portfolio: { eyebrow: 'Inspire-se', title: 'Um pouco do que fazemos', all: 'Todos', rental: 'Aluguel', decoration: 'Decoração', pickup: 'Pegue e monte', action: 'Pedir no WhatsApp' },
    how: { eyebrow: 'Leve e gostoso', title: 'Como funciona', steps: [{ title: 'Conte seu sonho', body: 'Fale com a gente sobre a data, o tema e o que você imaginou.' }, { title: 'A gente cria', body: 'Montamos uma proposta cheia de detalhes e carinho para você.' }, { title: 'É hora de celebrar', body: 'Você recebe tudo pronto para viver um dia inesquecível.' }] },
    about: { eyebrow: 'Feito com carinho', title: 'Festas com alma, beleza e leveza.', body: 'A [NOME] nasceu para transformar momentos simples em histórias que ficam. Acreditamos que celebrar é cuidar dos detalhes — e que cada família merece uma festa tão especial quanto suas memórias.', signature: 'Com carinho, equipe [NOME]' },
    faq: { eyebrow: 'Ainda ficou alguma dúvida?', title: 'Perguntas frequentes', questions: [{ q: 'Com quanto tempo devo reservar?', a: 'Recomendamos reservar com 30 dias de antecedência. Para datas especiais, fale com a gente quanto antes.' }, { q: 'Vocês atendem a minha cidade?', a: 'Atendemos a região e também enviamos kits Pegue e Monte. Consulte disponibilidade pelo WhatsApp.' }, { q: 'Posso personalizar meu pedido?', a: 'Sim! Adoramos criar propostas únicas. Conte sua ideia e vamos pensar juntos.' }] },
    contact: { eyebrow: 'Vamos criar juntos?', title: 'Sua próxima festa começa aqui.', body: 'Fale com a gente e conte como podemos deixar seu momento ainda mais especial.', cta: 'Chamar no WhatsApp' },
    footer: 'Feito para celebrar o que realmente importa.'
  },
  es: { nav: { portfolio: 'Portafolio', how: 'Cómo funciona', about: 'Sobre nosotros', faq: 'Preguntas', contact: 'Contacto' }, hero: { eyebrow: 'Fiestas que se vuelven recuerdos', title: 'Pequeños detalles. Grandes celebraciones.', body: 'Decoración afectiva y piezas encantadoras para hacer cada cumpleaños único.', cta: 'Hablar por WhatsApp', secondary: 'Ver portafolio' }, categories: { eyebrow: 'A tu manera', title: 'Elige cómo celebrar', rental: 'Alquiler de piezas', rentalBody: 'Piezas únicas para crear tu composición.', decoration: 'Decoración', decorationBody: 'Montamos todo con cuidado y personalidad.', pickup: 'Recoge y monta', pickupBody: 'Kits prácticos para celebrar a tu ritmo.' }, portfolio: { eyebrow: 'Inspírate', title: 'Un poco de lo que hacemos', all: 'Todos', rental: 'Alquiler', decoration: 'Decoración', pickup: 'Recoge y monta', action: 'Pedir por WhatsApp' }, how: { eyebrow: 'Fácil y bonito', title: 'Cómo funciona', steps: [{ title: 'Cuéntanos tu sueño', body: 'Háblanos de la fecha, el tema y lo que imaginaste.' }, { title: 'Nosotros creamos', body: 'Preparamos una propuesta llena de detalles y cariño.' }, { title: 'Es hora de celebrar', body: 'Recibes todo listo para vivir un día inolvidable.' }] }, about: { eyebrow: 'Hecho con cariño', title: 'Fiestas con alma, belleza y ligereza.', body: '[NOMBRE] nació para transformar momentos simples en historias que permanecen. Creemos que celebrar es cuidar los detalles.', signature: 'Con cariño, equipo [NOMBRE]' }, faq: { eyebrow: '¿Aún tienes dudas?', title: 'Preguntas frecuentes', questions: [{ q: '¿Con cuánto tiempo debo reservar?', a: 'Recomendamos reservar con 30 días de antelación.' }, { q: '¿Atienden mi ciudad?', a: 'Atendemos la región y también enviamos kits Recoge y monta.' }, { q: '¿Puedo personalizar mi pedido?', a: '¡Sí! Nos encanta crear propuestas únicas.' }] }, contact: { eyebrow: '¿Creamos juntos?', title: 'Tu próxima fiesta comienza aquí.', body: 'Háblanos y cuéntanos cómo podemos hacer tu momento aún más especial.', cta: 'Llamar por WhatsApp' }, footer: 'Hecho para celebrar lo que realmente importa.' },
  en: { nav: { portfolio: 'Portfolio', how: 'How it works', about: 'About us', faq: 'FAQ', contact: 'Contact' }, hero: { eyebrow: 'Parties that become memories', title: 'Small details. Big celebrations.', body: 'Thoughtful styling and charming pieces to make every birthday feel personal.', cta: 'Chat on WhatsApp', secondary: 'View portfolio' }, categories: { eyebrow: 'Your way', title: 'Choose how to celebrate', rental: 'Piece rental', rentalBody: 'Unique pieces to create your own setup.', decoration: 'Decoration', decorationBody: 'We style everything with care and personality.', pickup: 'Pick up & style', pickupBody: 'Practical kits to celebrate at your pace.' }, portfolio: { eyebrow: 'Get inspired', title: 'A little of what we do', all: 'All', rental: 'Rental', decoration: 'Decoration', pickup: 'Pick up & style', action: 'Ask on WhatsApp' }, how: { eyebrow: 'Easy and lovely', title: 'How it works', steps: [{ title: 'Tell us your dream', body: 'Share the date, theme and everything you imagined.' }, { title: 'We create', body: 'We prepare a thoughtful proposal made just for you.' }, { title: 'Time to celebrate', body: 'Everything arrives ready for an unforgettable day.' }] }, about: { eyebrow: 'Made with care', title: 'Parties with soul, beauty and ease.', body: '[NOME] was born to turn simple moments into stories that stay. We believe celebrating means caring about the details.', signature: 'With care, the [NOME] team' }, faq: { eyebrow: 'Still have questions?', title: 'Frequently asked questions', questions: [{ q: 'How early should I book?', a: 'We recommend booking 30 days in advance.' }, { q: 'Do you serve my city?', a: 'We serve the region and also ship Pick up & style kits.' }, { q: 'Can I customize my order?', a: 'Yes! We love creating unique proposals.' }] }, contact: { eyebrow: 'Shall we create together?', title: 'Your next party starts here.', body: 'Tell us how we can make your moment even more special.', cta: 'Chat on WhatsApp' }, footer: 'Made to celebrate what truly matters.' }
} as const

export const categoryLabel = (category: PartyItem['category'], t: (typeof translations)['pt']) => ({ rental: t.categories.rental, decoration: t.categories.decoration, pickup: t.categories.pickup }[category])

export const whatsappUrl = (message: string) => `https://wa.me/55[NUMERO]?text=${encodeURIComponent(message)}`
